[package]

name = "falcon"
version = "0.0.1"
description = "Something cool."
authors = ["Jonathan Reem <jonathan.reem@gmail.com>"]
repository = "https://github.com/reem/falcon"
readme = "README.md"
license = "MIT"
keywords = ["web", "railgun"]

[dependencies]
mio = "*"
hyper = "*"
httparse = "*"
iobuf = "*"

[dev-dependencies]
stainless = "*"

